theme: jekyll-theme-hacker
title: Raihasen's page
description: Preparing for technical interviews. Usefull links for preparing to Google, Facebook & Bloomberg Software Engineer Full Time and Intern position interviews.
